name: Build Develop Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: install ng
        run: npm install -g @angular/cli@latest
      - name: Pull code master
        run: git pull
      - name: Create Build
        run: ng build --prod
        env:
          CI: false
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        run: |
          echo "$SERVER_SSH_KEY"



