name: Build Develop Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy to Server
        run: |
          echo ${{ env.SERVER_SSH_KEY }}
        env:
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}



